spring.application.name=SpringSecurityEx

spring.security.user.name=shubham
spring.security.user.password=dhage

spring.datasource.url=jdbc:postgresql://localhost:5432/shubhamd
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
