spring.application.name=spring-stream-backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/learn
spring.datasource.username=root
spring.datasource.password=root1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Maximum file size allowed for a single upload
spring.servlet.multipart.max-file-size=1000MB

# Maximum request size allowed for multipart/form-data requests
spring.servlet.multipart.max-request-size=1000MB

files.video=videos/
files.video.hsl=videos_hsl/
